wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 128
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0.01
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 128
num_hidden_layers:
  value: 2
optimizer:
  value: stochastic_gradient_descent
weight_init:
  value: xavier_initialization
