wandb_version: 1

activation:
  value: relu_function
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error_function
momentum:
  value: 0.9
neurons:
  value: 128
num_hidden_layers:
  value: 4
optimizer:
  value: vanilla_gradient_descent
weight_init:
  value: xavier_initialization
