wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 4
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 5
lambd:
  value: 0.5
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error_function
momentum:
  value: 0.5
neurons:
  value: 32
num_hidden_layers:
  value: 5
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: random_initialization
