wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 32
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 5
lambd:
  value: 0.5
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 64
num_hidden_layers:
  value: 3
optimizer:
  value: nestorov_accelarated_gradient_descent
weight_init:
  value: xavier_initialization
