wandb_version: 1

activation:
  value: relu_function
batch_size:
  value: 128
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0.0005
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy_function
momentum:
  value: 0.8
neurons:
  value: 128
num_hidden_layers:
  value: 4
optimizer:
  value: rms_prop
weight_init:
  value: xavier_initialization
