wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 128
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 5
lambd:
  value: 0
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error_function
momentum:
  value: 0.5
neurons:
  value: 32
num_hidden_layers:
  value: 4
optimizer:
  value: vanilla_gradient_descent
weight_init:
  value: random_initialization
