wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 40
lambd:
  value: 0.5
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_function
momentum:
  value: 0.8
neurons:
  value: 128
num_hidden_layers:
  value: 4
optimizer:
  value: rms_prop
weight_init:
  value: random_initialization
