wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 4
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0.5
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy_function
momentum:
  value: 0.8
neurons:
  value: 32
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: xavier_initialization
