wandb_version: 1

activation:
  value: relu_function
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 20
lambd:
  value: 0.0005
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error_function
momentum:
  value: 0.8
neurons:
  value: 128
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: xavier_initialization
