wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0
learning_rate:
  value: 1.0e-05
loss:
  value: mean_squared_error_function
momentum:
  value: 0.9
neurons:
  value: 16
num_hidden_layers:
  value: 1
optimizer:
  value: adam
weight_init:
  value: xavier_initialization
