wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 40
lambd:
  value: 0
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_function
momentum:
  value: 0.8
neurons:
  value: 64
num_hidden_layers:
  value: 1
optimizer:
  value: stochastic_gradient_descent
weight_init:
  value: xavier_initialization
