wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 16
num_hidden_layers:
  value: 1
optimizer:
  value: stochastic_gradient_descent
weight_init:
  value: random_initialization
