wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 4
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error_function
momentum:
  value: 0.8
neurons:
  value: 64
num_hidden_layers:
  value: 4
optimizer:
  value: nadam
weight_init:
  value: xavier_initialization
