wandb_version: 1

activation:
  value: relu_function
batch_size:
  value: 8
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 32
num_hidden_layers:
  value: 1
optimizer:
  value: nesterov_accelarated_gradient_descent
weight_init:
  value: random_initialization
