wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1677747315.727509
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: tanh_function
batch_size:
  desc: null
  value: 4
beta:
  desc: null
  value: 0.9
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.99
epochs:
  desc: null
  value: 20
lambd:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.01
loss:
  desc: null
  value: mean_squared_error_function
momentum:
  desc: null
  value: 0.8
neurons:
  desc: null
  value: 64
num_hidden_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: nadam
weight_init:
  desc: null
  value: xavier_initialization
