wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 5
lambd:
  value: 0.0005
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error_function
momentum:
  value: 0.9
neurons:
  value: 128
num_hidden_layers:
  value: 3
optimizer:
  value: nestorov_accelarated_gradient_descent
weight_init:
  value: xavier_initialization
