wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 256
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0.5
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 32
num_hidden_layers:
  value: 5
optimizer:
  value: vanilla_gradient_descent
weight_init:
  value: random_initialization
