wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 4
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0.5
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error_function
momentum:
  value: 0.5
neurons:
  value: 64
num_hidden_layers:
  value: 4
optimizer:
  value: rms_prop
weight_init:
  value: random_initialization
