wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_function
momentum:
  value: 0.5
neurons:
  value: 32
num_hidden_layers:
  value: 5
optimizer:
  value: stochastic_gradient_descent
weight_init:
  value: random_initialization
