wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 10
lambd:
  value: 0.5
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_function
momentum:
  value: 0.5
neurons:
  value: 64
num_hidden_layers:
  value: 5
optimizer:
  value: rms_prop
weight_init:
  value: xavier_initialization
