wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 4
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
lambd:
  value: 0
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 64
num_hidden_layers:
  value: 2
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: random_initialization
