wandb_version: 1

activation:
  value: identity_function
batch_size:
  value: 16
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 40
lambd:
  value: 0.0005
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_function
momentum:
  value: 0.9
neurons:
  value: 64
num_hidden_layers:
  value: 5
optimizer:
  value: rms_prop
weight_init:
  value: random_initialization
