wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 4
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
lambd:
  value: 0.0005
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error_function
momentum:
  value: 0.8
neurons:
  value: 32
num_hidden_layers:
  value: 5
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: xavier_initialization
