wandb_version: 1

activation:
  value: tanh_function
batch_size:
  value: 4
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 5
lambd:
  value: 0
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_function
momentum:
  value: 0.8
neurons:
  value: 32
num_hidden_layers:
  value: 3
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: xavier_initialization
