wandb_version: 1

activation:
  value: sigmoid_function
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 5
lambd:
  value: 0.5
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error_function
momentum:
  value: 0.5
neurons:
  value: 64
num_hidden_layers:
  value: 4
optimizer:
  value: nadam
weight_init:
  value: xavier_initialization
